# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Yes Chef' do

pod 'Alamofire', '~> 3.1'
pod 'AlamofireImage', '~> 2.3'
pod 'SwiftyJSON', '~> 2.3'
pod 'StringScore_Swift', '~> 0.1'

end

